export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const SET_SEARCH_BY = 'SET_SEARCH_BY';
export const SET_SORT_BY = 'SET_SORT_BY';
export const SET_SELETED_MOVIE_ID = 'SET_SELECTED_MOVIE_ID';
export const RESET_SELECTED_MOVIE = 'RESET_SELECTED_MOVIE';
export const INCREASE_OFFSET = 'INCREASE_OFFSET';
export const RESET_OFFSET = 'RESET_OFFSET';
